version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy:v1.29.1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9999:9999" 
      - "9901:9901"
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
    depends_on:
      - api-01

  # redis-hipster:
  #   image: redis:7.2.4
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.2"
  #         memory: "50M"
  #   depends_on:
  #     - postgres-hipster

  postgres-hipster:
    image: postgres:16
    environment:
      POSTGRES_DB: rinhadebackend
      POSTGRES_USER: fidelissauro
      POSTGRES_PASSWORD: doutorequemtemdoutorado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200M"

  api-01:
    image: cosmtrek/air
    container_name: api-hipster-01
    ports:
      - 8080:8080
    working_dir: /rinha-golang-hipster
    environment:
      - DATABASE_HOST=postgres-hipster
      - DATABASE_PORT=5432
      - DATABASE_DB=rinhadebackend
      - DATABASE_USER=fidelissauro
      - DATABASE_PASSWORD=doutorequemtemdoutorado
      - CACHE_HOST=redis-hipster
      - CACHE_PORT=6379
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.3"
    #       memory: "125M"
    volumes:
      - ./:/rinha-golang-hipster
    depends_on:
      # - redis-hipster
      - postgres-hipster

  # api-02:
  #   image: rinha-2024:latest
  #   container_name: api-02
  #   ports:
  #     - 8082:8080
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_DB=rinhadebackend
  #     - DATABASE_USER=fidelissauro
  #     - DATABASE_PASSWORD=doutorequemtemdoutorado
  #     - CACHE_HOST=redis
  #     - CACHE_PORT=6379
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.3"
  #         memory: "125M"
  #   depends_on:
  #     - redis
  #     - postgres
      
volumes:
  redis_data:
  postgres_data:
